name: myapp-test-api

include:
  - path:
      - services/docker-compose.mongodb.yml
      - networks/docker-compose.custom.yml
      - volumes/docker-compose.mongodb.yml

services:
  backend-core:
    restart: unless-stopped
    tmpfs: /tmp
    ports:
      - '9229:9229'
      - '4020:4020'
    networks:
      - front-tier
      - back-tier
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
      - ../coverage:/app/coverage
    env_file: ../.env
    environment:
      - NODE_ENV=test
      - MONGO_DATABASE=test
    build:
      context: ..
      dockerfile: docker/Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
    depends_on:
      mongodb-core:
        condition: service_started
        restart: true
    links:
      - mongodb-core
    command:
      [
        'npx',
        'jest',
        '--runInBand',
        '--config',
        'jest.config.js',
        '--testTimeout',
        '1500000',
        '--detectOpenHandles',
        'src/tests/api/user.spec.ts',
      ]
