name: myapp-dev

include:
  - path:
      - services/docker-compose.mongodb.yml
      - networks/docker-compose.custom.yml
      - volumes/docker-compose.mongodb.yml

services:
  backend-core:
    restart: unless-stopped
    tmpfs: /tmp
    ports:
      - '9229:9229'
      - '4020:4020'
    networks:
      - front-tier
      - back-tier
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
    env_file: ../.env
    environment:
      - NODE_ENV=development
    build:
      context: ..
      dockerfile: docker/Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      mongodb-core:
        condition: service_started
        restart: true
    links:
      - mongodb-core
    command:
      [
        'npx',
        'nodemon',
        '--exec',
        'node',
        '--inspect=0.0.0.0:9229',
        '--require',
        'ts-node/register',
        'src/server.ts'
      ]
