services:
  mongodb-core:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    networks:
      - back-tier
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    command: [ 'mongod', '--quiet', '--logpath', '/dev/null' ]
