services:
  mongodb-core:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    # Commented for scaling the containers (Docker swarm)
    # container_name: mongodb-core-c
    restart: unless-stopped # Ignored if specified deploy.restart_policy (Docker swarm)
    ports:
      - '27017:27017'
    networks:
      - back-tier
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
